---
tests:
  # Ladder tests
  - name: ladder1.sgf
    sgf: ladder1.sgf
    group: ladder
    move: black
    no_move:
      - P7
  - name: ladder2
    sgf: ladder2.sgf
    group: ladder
    move: black
    no_move:
      - G4
  - name: ladder3
    sgf: ladder3.sgf
    group: ladder
    move: white
    no_move:
      - P11
  - name: ladder4
    sgf: ladder4.sgf
    group: ladder
    move: black
    no_move:
      - P6
  - name: ladder5
    sgf: ladder5.sgf
    group: ladder
    move: white
    no_move:
      - J6
  - name: ladder6
    sgf: ladder6.sgf
    group: ladder
    move: white
    no_move:
      - F14
  - name: ladder7
    sgf: ladder7.sgf
    group: ladder
    move: white
    no_move:
      - G6
  - name: ladder8
    sgf: ladder8.马天放.2018.3.7.sgf
    group: ladder
    number: 41
    move: black
    no_move:
      - G16
  - name: ladder9
    sgf: 误逃征子_20180308.sgf
    group: ladder
    move: black
    no_move:
      - E11
  - name: ladder10
    sgf: 看错征子_20180308.sgf
    group: ladder
    number: 156
    move: white
    max_win_rate: 40
  - name: ladder11
    sgf: 10b-545权重征子bug.sgf
    group: ladder
    number: 56
    move: white
    no_move:
      - K7
  - name: 33point-ladder
    sgf: aq_lz_33point_ladder.sgf
    group: ladder
    number: 15
    move: black
    no_move:
      - Q7
  - name: cut-ladder-misread
    sgf: ladder_misread_by_cut_52_20180308.sgf
    group: ladder
    number: 52
    move: white
    no_move:
      - G3
  - name: ladder12
    sgf: 陈文政_LeelaZero_20180315.sgf
    group: ladder
    number: 106
    move: white
    no_move:
      - M9
  - name: ladder13
    sgf: 大斜征子.sgf
    group: ladder
    number: 16
    move: white
    no_move:
      - S6
  - name: ladder14
    sgf: ladder14.sgf
    group: ladder
    number: 59
    move: black
    no_move:
      - E16
  - name: ladder15
    sgf: 预判征子.sgf
    group: ladder
    number: 34
    move: white
    no_move:
      - C10
  - name: ladder16
    sgf: 12496265-125-RoyalZero-lizf123.sgf
    group: ladder
    number: 58
    move: white
    no_move:
      - O5

  # Life & Death tests
  - name: make_life1
    sgf: lifedeath1.sgf
    group: lifedeath
    move: white
    yes_move:
      - M10
  - name: make_life2
    sgf: 娱乐版围棋执黑中盘胜alphaleela_20180308.sgf
    group: lifedeath
    number: 116
    move: white
    yes_move:
      - M19
  - name: make_life3
    sgf: 隐忍黑衣人_alphaleela_20180307.sgf
    group: lifedeath
    number: 217
    move: white
    yes_move:
      - P9
      - Q9
  - name: j_group_live1
    sgf: lifedeath2.sgf
    group: lifedeath
    number: 222
    move: white
    yes_move:
      - S18 # This moves makes life for white
      - R18 # This also works, especially white has advantage
  - name: make_life4
    sgf: 2017围丙第二轮_胡然闵_杨冬.sgf
    group: lifedeath
    number: 153
    move: black
    yes_move:
      - M1
  - name: make_life5
    sgf: 双活1.sgf
    group: lifedeath
    number: 196
    move: white
    yes_move:
      - T9
  - name: make_life6
    sgf: 第8届姜堰三国女子擂台赛第5局_李赫_金多瑛.sgf
    group: lifedeath
    number: 174
    move: white
    yes_move:
      - F9
  - name: kill1
    sgf: 第8届姜堰三国女子擂台赛第5局_李赫_金多瑛.sgf
    group: lifedeath
    number: 175
    move: black
    yes_move:
      - G9
  - name: make_life7
    sgf: 打劫走成净死.sgf
    group: lifedeath
    number: 119
    move: black
    yes_move:
      - J1
  - name: j_group_live2
    sgf: 大猪嘴.sgf
    group: lifedeath
    number: 52
    move: white
    yes_move:
      - R1

  # Large group sensitive tests
  - name: largegroup_no_liberty_dead
    sgf: zen7-LZaf9.sgf
    group: largegroup
    move: white
    max_win_rate: 10
  - name: largegroup_some_liberty_dead
    sgf: zen7-LZaf9.sgf
    group: largegroup
    number: 256
    move: white
    max_win_rate: 10
  - name: largegroup_atari1
    sgf: largegroup_atari1.sgf
    group: largegroup
    number: 294
    move: white
    yes_move:
      - E1
  - name: largegroup_dead1
    sgf: zen7_LZ.sgf
    group: largegroup
    move: white
    max_win_rate: 40
  - name: largegroup_dead2
    sgf: jinduan_LZ.sgf
    group: largegroup
    move: white
    max_win_rate: 40
  - name: largegroup_dead3
    sgf: zen7_lz_largegroup_20180306.sgf
    group: largegroup
    number: 206
    move: white
    max_win_rate: 40
  - name: largegroup_dead4
    sgf: 娱乐版围棋执黑中盘胜alphaleela_20180308.sgf
    group: largegroup
    number: 196
    move: white
    max_win_rate: 30
  - name: dead_group_misread
    sgf: 11990416-120-Bifron-RoyalZero.sgf
    group: largegroup
    number: 117
    move: black
    max_win_rate: 40
  - name: largegroup_atari2
    sgf: 毒奶菇_看不见叫吃_20180325.sgf
    group: largegroup
    number: 358
    move: white
    yes_move:
      - E13
      - F11

  - name: endgame1
    sgf: endgame1.sgf
    group: endgame
    number: 289
    move: black
    yes_move:
      - S19

  - name: endgame2
    sgf: endgame2.sgf
    group: endgame
    number: 270
    move: white
    no_move:
      - G19

  - name: endgame3
    sgf: AGZ_40b_017.sgf
    group: endgame
    number: 319
    move: black
    yes_move:
      - T10 # Analyzed by Yang Dong 4P, only winning move

  - name: endgame4
    sgf: AGZ_40b_017.sgf
    group: endgame
    number: 268
    move: white
    yes_move:
      - J12 # Analyzed by Yang Dong 4P, white can win with this move

  - name: endgame5 # Analyzed by Yang Dong 4P
    sgf: 2018贺岁杯第二局_一力辽_柯洁.sgf
    group: endgame
    number: 217
    move: black
    yes_move:
      - E8
      - F8 # F8 also works

  - name: endgame6 # Analyzed by Yang Dong 4P
    sgf: 2018贺岁杯第二局_一力辽_柯洁2.sgf
    group: endgame
    number: 227
    move: black
    yes_move:
      - E1
      - J1

  - name: endgame7
    sgf: AGZ_40b_017.sgf
    group: endgame
    move: white
    max_win_rate: 10

  - name: reduce_liberty_misread
    sgf: 低K官子看错输棋.sgf
    group: endgame
    number: 322
    move: white
    yes_move:
      - H7
      - K8

  # Capture Race tests
  - name: race1
    sgf: MaTianFang_LZ_20180227.sgf
    group: race
    number: 63
    move: black
    yes_move:
      - S11

  - name: race2
    sgf: MaTianFang_LZ_20180227.sgf
    group: race
    number: 65
    move: black
    yes_move:
      - R10

  - name: race3
    sgf: somebot-godiva-2.sgf
    group: race
    number: 238
    move: white
    yes_move:
      - T17
      - M17

  - name: race4
    sgf: 12383186-296-inelasticneutron-RoyalZero.sgf
    group: race
    number: 291
    move: black
    yes_move:
      - A19
      - C11
